version: "3"
services:
  lazy-teacher:
    env_file: .env
    ports:
      - 5000:5000
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lazy-teacher
    volumes:
      - ./:/usr/local/lazy-teacher
    command: python app.py
